adc1=float(input("请输入第一个数"))
adc2=float(input("请输入第二个数"))
adc3=float(input("请输入第三个数"))
adc4=float(input("请输入第四个数"))
adc5=float(input("请输入第五个数"))
adc6=float(input("请输入第六个数"))
adc7=float(input("请输入第七个数"))
adc8=float(input("请输入第八个数"))
adc9=float(input("请输入第九个数"))
adc10=float(input("请输入第十个数"))
print(adc1+adc2+adc3+adc4+adc5+adc6+adc7+adc8+adc9+adc10)



adc1=float(input("请输入第一个数"))
adc2=float(input("请输入第二个数"))
adc3=float(input("请输入第三个数"))
adc4=float(input("请输入第四个数"))
adc5=float(input("请输入第五个数"))
adc6=float(input("请输入第六个数"))
adc7=float(input("请输入第七个数"))
adc8=float(input("请输入第八个数"))
adc9=float(input("请输入第九个数"))
adc10=float(input("请输入第十个数"))
print(adc1+adc2+adc3+adc4+adc5+adc6+adc7+adc8+adc9+adc10)
print(max(adc1,adc2,adc3,adc4,adc5,adc6,adc7,adc8,adc9,adc10))
num=(adc1+adc2+adc3+adc4+adc5+adc6+adc7+adc8+adc9+adc10)
print(num/10)

